"""create initial tables

Revision ID: b24375ec9f9b
Revises: 
Create Date: 2026-08-17 17:57:06.849469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24375ec9f9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'WARRANTY_EXPIRED', 'NEEDS_REPLACEMENT', name='customer_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('equipments',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.Enum('BATTERY', 'INVERTER', 'SOLAR', 'OTHER', name='equipment_type_enum'), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REPLACED', 'DAMAGED', 'REMOVED', name='equipment_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_customer_id'), 'equipments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_index(op.f('ix_equipments_serial_number'), 'equipments', ['serial_number'], unique=True)
    op.create_index(op.f('ix_equipments_status'), 'equipments', ['status'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('INSTALLATION', 'ROUTINE', 'EMERGENCY', name='maintenance_type_enum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'PENDING', name='payment_method_enum'), nullable=False),
    sa.Column('water_filled', sa.Boolean(), nullable=False),
    sa.Column('voltage_checked', sa.Boolean(), nullable=False),
    sa.Column('voltage_reading', sa.String(length=20), nullable=True),
    sa.Column('terminal_cleaned', sa.Boolean(), nullable=False),
    sa.Column('battery_replaced', sa.Boolean(), nullable=False),
    sa.Column('wiring_checked', sa.Boolean(), nullable=False),
    sa.Column('fuse_changed', sa.Boolean(), nullable=False),
    sa.Column('complaint_resolved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_date'), 'maintenance_records', ['maintenance_date'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_type'), 'maintenance_records', ['maintenance_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_maintenance_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_equipments_status'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_serial_number'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_customer_id'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
